/** GST POS codes for GSTR-1 place of supply selector (code — label). */
export const INDIAN_STATE_POS_OPTIONS: readonly { readonly code: string; readonly label: string }[] =
  [
    { code: '01', label: '01 — Jammu & Kashmir' },
    { code: '02', label: '02 — Himachal Pradesh' },
    { code: '03', label: '03 — Punjab' },
    { code: '04', label: '04 — Chandigarh' },
    { code: '05', label: '05 — Uttarakhand' },
    { code: '06', label: '06 — Haryana' },
    { code: '07', label: '07 — Delhi' },
    { code: '08', label: '08 — Rajasthan' },
    { code: '09', label: '09 — Uttar Pradesh' },
    { code: '10', label: '10 — Bihar' },
    { code: '11', label: '11 — Sikkim' },
    { code: '12', label: '12 — Arunachal Pradesh' },
    { code: '13', label: '13 — Nagaland' },
    { code: '14', label: '14 — Manipur' },
    { code: '15', label: '15 — Mizoram' },
    { code: '16', label: '16 — Tripura' },
    { code: '17', label: '17 — Meghalaya' },
    { code: '18', label: '18 — Assam' },
    { code: '19', label: '19 — West Bengal' },
    { code: '20', label: '20 — Jharkhand' },
    { code: '21', label: '21 — Odisha' },
    { code: '22', label: '22 — Chhattisgarh' },
    { code: '23', label: '23 — Madhya Pradesh' },
    { code: '24', label: '24 — Gujarat' },
    { code: '26', label: '26 — Dadra & Nagar Haveli and Daman & Diu' },
    { code: '27', label: '27 — Maharashtra' },
    { code: '29', label: '29 — Karnataka' },
    { code: '30', label: '30 — Goa' },
    { code: '31', label: '31 — Lakshadweep' },
    { code: '32', label: '32 — Kerala' },
    { code: '33', label: '33 — Tamil Nadu' },
    { code: '34', label: '34 — Puducherry' },
    { code: '35', label: '35 — Andaman & Nicobar Islands' },
    { code: '36', label: '36 — Telangana' },
    { code: '37', label: '37 — Andhra Pradesh' },
    { code: '38', label: '38 — Ladakh' },
    { code: '97', label: '97 — Other Territory' },
    { code: '96', label: '96 — Foreign Country' },
    { code: '99', label: '99 — Centre Jurisdiction' },
  ];
